compile_model:
	g++ -O3 -o IsingModel2D.out IsingModel2D.cpp

2x2:
	g++ -O3 -o 2x2_lattice.out 2x2_lattice.cpp IsingModel2D.cpp

2x2MCS:
	g++ -O3 -o 2x2_lattice_MCS.out 2x2_lattice_MCS.cpp IsingModel2D.cpp

20x20:
	g++ -O3 -o 20x20_lattice.out 20x20_lattice.cpp IsingModel2D.cpp




